# Generated by Django 2.2.4 on 2019-09-28 20:29

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('medoc', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Profile',
        ),
    ]
