# Generated by Django 2.2.4 on 2019-10-25 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medoc', '0006_auto_20191025_1352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinstanceaccess',
            name='user_status',
        ),
        migrations.DeleteModel(
            name='UserStatus',
        ),
    ]
