# Generated by Django 2.2.4 on 2019-11-04 10:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medoc', '0009_profile_middle_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='mail',
        ),
        migrations.AlterField(
            model_name='profile',
            name='login',
            field=models.CharField(default=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL), help_text='Додайте користувача для M.E.Doc', max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='password',
            field=models.CharField(help_text='Додайте пароль для використання M.E.Doc', max_length=200),
        ),
    ]
