# Generated by Django 2.2.4 on 2019-11-08 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medoc', '0011_auto_20191108_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='external_user',
            field=models.BooleanField(default=False, help_text='Статус зовнішнього користувача'),
        ),
    ]
