# Generated by Django 2.2.4 on 2019-11-12 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medoc', '0014_auto_20191112_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='num_id',
            field=models.CharField(help_text='Код ЄДРПО', max_length=9),
        ),
        migrations.AlterField(
            model_name='organization',
            name='status_organization',
            field=models.CharField(choices=[('a', 'Активна'), ('d', 'Не активна'), ('l', 'Ліквідується'), ('s', 'Продано')], default='a', help_text='Статус організації', max_length=100),
        ),
    ]
